import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Toaster} from "react-hot-toast";
import {getServerSession} from "next-auth";
import AuthProvider from "@/app/api/auth/[...nextauth]/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const session = getServerSession()


    return (
    <html lang="en">
    <AuthProvider session={session}>
      <body className={inter.className}>
      <Toaster/>
      {children}
      </body>
    </AuthProvider>
    </html>
  );
}
