# Generated by Django 5.0.6 on 2024-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="uniqueId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
