# Generated by Django 5.0.6 on 2024-07-17 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_client_uniqueid"),
        ("invoice", "0003_remove_invoice_date_created_remove_invoice_duedate_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
