# Generated by Django 5.0.6 on 2024-07-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
    ]
