# Generated by Django 5.0.6 on 2024-08-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='MonthlySummary',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
