# Generated by Django 5.0.6 on 2024-08-14 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='report.client'),
        ),
    ]
