# Generated by Django 5.0.6 on 2024-07-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0004_profile_company_profile_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
