# Generated by Django 5.0.6 on 2024-07-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0006_profile_ein_number_profile_tax_id_user_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
