# Generated by Django 5.0.6 on 2024-07-16 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0007_profile_zip_code_user_zip_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="website",
        ),
    ]
