# Generated by Django 5.0.6 on 2024-07-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0008_remove_profile_gender_remove_profile_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ein_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
