# Generated by Django 5.0.6 on 2024-07-17 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0009_remove_user_address_remove_user_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="company",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="ein_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="website",
        ),
    ]
