# Generated by Django 5.0.6 on 2024-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0010_remove_profile_company_remove_profile_ein_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(
                choices=[("NY", "New York"), ("CA", "California"), ("TX", "Texas")],
                default="TX",
                max_length=100,
            ),
        ),
    ]
