# Generated by Django 5.0.6 on 2024-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0011_alter_profile_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(default=True),
        ),
    ]
