# Generated by Django 5.0.6 on 2024-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0012_user_is_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(default=False),
        ),
    ]
