# Generated by Django 5.0.6 on 2024-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clientName", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "clientLogo",
                    models.ImageField(
                        default="default_logo.jpg", upload_to="company_logos"
                    ),
                ),
                (
                    "addressLine1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "states",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NY", "New York"),
                            ("CA", "California"),
                            ("TX", "Texas"),
                        ],
                        max_length=100,
                    ),
                ),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "phoneNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emailAddress",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("taxNumber", models.CharField(blank=True, max_length=100, null=True)),
                ("uniqueId", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(choices=[("$", "USD")], default="R", max_length=100),
        ),
    ]
