# Generated by Django 5.0.6 on 2024-07-17 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_setting_delete_settings_alter_product_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="dueDate",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="number",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="paymentTerms",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="status",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="title",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="uniqueId",
        ),
        migrations.AddField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(choices=[("$", "USD")], default="$", max_length=100),
        ),
    ]
