# Generated by Django 5.0.6 on 2024-07-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_paymentterms'),
        ('store', '0004_remove_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='store.order'),
        ),
    ]
