# Generated by Django 5.0.6 on 2024-07-28 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_orders'),
        ('store', '0005_remove_order_address_remove_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='orders',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='store.order'),
        ),
    ]
