# Generated by Django 5.0.6 on 2024-07-30 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_invoice_orders_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dueDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
